### PR TITLE
fix #6008:improve the home section of neo frontend

### LINKED ISSUE #6008: Neo Website Home Section
Related to the Hacktoberfest Welcome ticket: https://github.com/neomjs/neo/issues/5963 (Please read this ticket first)

Another shout-out to all designers who would like to participate in the hacktoberfest event.

Screenshot 2024-10-02 at 15 58 12

The very first page when opening the Neo.mjs website still looks odd.

@mxmrtns had the idea to make the tag-line the biggest element, the logo smaller on top and the content text centered.
Rationale: Neo.mjs is not yet a known brand, so the tag-line provides the most value.

Maybe it could go a bit into this direction: https://nuxt.com/

Looking forward to your ideas!

Thanks in advance,
Tobi

### PR DESCRIPTION
**Pull request by TusharMohapatra07**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, _not_ the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

**Other information:**
This PR is linked with issue #6008. I have improved the look of the neo homepage by making the tagline significantly big such that it won't go unnoticed. Also, I've added a background pattern which complements the look of homepage.

### CODE REVIEW

**Comment by tobiu** [comment]
hi @TusharMohapatra07,

the design-changes look good. One very important requirement, before i can accept & merge this PR:
please do not change the default formatting, otherwise it becomes very hard to spot for others what changed.

Meaning: 4 spaces & block formatting (align on colon). You can just add another commit to this PR (no need for a new one) and I will accept it afterwards.

Ideas for a follow-up PR: we could switch the h1 & h2 tags (h2 for the logo-text, h1 for the tag-line) => can be easily done inside the matching JS file.

We do have CSS vars for font-weight:
```
font-weight: var(--core-fontweight-semibold);
```

There is also one for bold (I think it equals 700 instead of 800). // var(--core-fontweight-bold);

Best regards,
Tobi

**Comment by TusharMohapatra07** [comment]
@tobiu please review

**Comment by TusharMohapatra07** [comment]
@tobiu please review. Also, I'll be followup PR that You're talking about.

**Comment by tobiu** [comment]
you hopefully know that you can review the changes too:
https://github.com/neomjs/neo/pull/6020/files

you got the 4 spaces indentation in there now, which is good. the align on colon part is missing, but i will fix it.

hacktoberfest approved.

**Comment by TusharMohapatra07** [comment]
@tobiu i think the commit named "fix spacing" with hash 85ad0ff did that but then i thought it was wrong.

**Comment by TusharMohapatra07** [comment]
By the was, thanks @tobiu for your patience and time. You were such welcoming and supportive.

**Pull request merged**
